# Generated by Django 5.2.13 on 2026-04-23 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoted_tips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tip',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_tips', to=settings.AUTH_USER_MODEL),
        ),
    ]
